In [8]:
from sklearn import preprocessing
import numpy as np

# Carga de datos.

In [9]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

# Limpieza de datos: estandarización.

In [10]:
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento

In [11]:
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [12]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

# Aplicamos los métodos "fit" y "transform" por separado

In [13]:
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


# Comprobar si las matrices estandarizadas son iguales

In [17]:
iguales = np.allclose(X_train_std, X_train_2_std)
print('¿Son las matrices iguales?:', iguales)

¿Son las matrices iguales?: True


# GitHub 

- [https://github.com/ndadri/Cuaderno_python2](https://github.com/ndadri/Cuaderno_python2) 