![jupyter](img/logoItq.png)

**Nombre:** *Adrián Falcones*

**Primer Modulo**

![jupyter](img/logoPy.png)

In [2]:
from sklearn import preprocessing
import numpy as np

# Carga de datos de entrenamiento

- Se crea una matriz con 3 instancias (filas) y 3 atributos (columnas)

In [3]:
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2. ],
                    [ 0.,  6., -3.]])
print("Datos de entrenamiento originales:")
print(X_train)

Datos de entrenamiento originales:
[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


# Limpieza de datos: normalización (MinMaxScaler)

- El objetivo es transformar los atributos al rango [0, 1]

In [4]:
normalizer = preprocessing.MinMaxScaler()

- 'fit_transform' calcula los mínimos/máximos y aplica la fórmula en un solo paso

In [5]:
X_train_norm = normalizer.fit_transform(X_train)

print("\nDatos de entrenamiento normalizados:")
print(X_train_norm)


Datos de entrenamiento normalizados:
[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


# Verificación de consistencia

- Comprobamos que aplicar 'fit' y luego 'transform' da el mismo resultado

In [6]:
X_train_2 = np.copy(X_train)
f = normalizer.fit(X_train) # Aprende los parámetros (min/max)
X_train_norm_2 = f.transform(X_train) # Aplica la transformación

print("\n¿Los métodos son equivalentes?:", np.array_equiv(X_train_norm, X_train_norm_2))


¿Los métodos son equivalentes?: True


# Normalizar un nuevo conjunto de datos (Test)

- **IMPORTANTE:** En test solo usamos 'transform'. No usamos 'fit' porque debemos usar la escala aprendida de los datos de entrenamiento.

In [7]:
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  4., -1.]])

In [8]:
X_test_norm = normalizer.transform(X_test)

print("\nNuevos datos de test normalizados (con la escala de entrenamiento):")
print(X_test_norm)


Nuevos datos de test normalizados (con la escala de entrenamiento):
[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


# GitHub 

- [https://github.com/ndadri/Cuaderno_python2](https://github.com/ndadri/Cuaderno_python2) 